# Generated by Django 4.2.4 on 2023-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('camelValue', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bpf', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('iq', models.IntegerField()),
                ('hair', models.CharField(max_length=50)),
                ('beard', models.CharField(max_length=50)),
                ('jewlery', models.CharField(max_length=50)),
            ],
        ),
    ]
