# Generated by Django 4.2.4 on 2023-08-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamelRechner', '0002_remove_person_bpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
