# Generated by Django 4.2.4 on 2023-08-14 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consumed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('calorie_count', models.FloatField()),
            ],
        ),
    ]
